version: '3.3'

services:
  registry:
    image: registry:2
    container_name: registry
    expose:
    - "5000"
    #environment:
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      #REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./registry-auth:/auth
      - ./registry-data:/data
      - ./registry-config.yml:/etc/docker/registry/config.yml
    networks:
      - zeeplay-workspace
  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    expose:
      - "80"
    environment:
      #- REGISTRY_URL=https://registry.zeeplay.ir
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
    networks:
      - zeeplay-workspace
networks:
  zeeplay-workspace:
    external:
      name: zeeplay-workspace
